<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

### Additional Exercise

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

In [2]:
#Create a random tensor with shape (7, 7).
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.9709, 0.1886, 0.7619, 0.1309, 0.2184, 0.3355, 0.0266],
        [0.3084, 0.9814, 0.9837, 0.0029, 0.5818, 0.8402, 0.5852],
        [0.8609, 0.9351, 0.2387, 0.2069, 0.4034, 0.5250, 0.2241],
        [0.8697, 0.9994, 0.4880, 0.2455, 0.4390, 0.6738, 0.5357],
        [0.7165, 0.3165, 0.7587, 0.6908, 0.4715, 0.0457, 0.8287],
        [0.6514, 0.0129, 0.1567, 0.0441, 0.6816, 0.4033, 0.2542],
        [0.4603, 0.1553, 0.2051, 0.2943, 0.4005, 0.4602, 0.5854]])

In [3]:

#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

# Assume tensor from step 2 is defined as follows (example tensor)
tensor1 = torch.randn(3, 7)  # Shape: (3, 7)

# Create another random tensor with shape (1, 7)
tensor2 = torch.randn(1, 7)  # Shape: (1, 7)

# Transpose tensor2 to make matrix multiplication possible
tensor2_transposed = tensor2.T  # Shape: (7, 1)

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_transposed)  # Result shape: (3, 1)

print("Result of matrix multiplication:\n", result)


Result of matrix multiplication:
 tensor([[-6.7335],
        [-8.9494],
        [-4.8085]])


In [4]:
#Set the random seed to 0 and do exercises 2 & 3 over again.

# Set the random seed to 0
torch.manual_seed(0)

# Exercise 2: Create a random tensor with shape (7, 7)
random_tensor_2 = torch.rand(7, 7)
print("Random Tensor (Exercise 2):\n", random_tensor_2)

# Exercise 3: Perform matrix multiplication
# Assume tensor from step 2 is defined as follows (example tensor)
tensor1 = torch.randn(3, 7)  # Shape: (3, 7)

# Create another random tensor with shape (1, 7)
tensor2 = torch.randn(1, 7)  # Shape: (1, 7)

# Transpose tensor2 to make matrix multiplication possible
tensor2_transposed = tensor2.T  # Shape: (7, 1)

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_transposed)  # Result shape: (3, 1)

print("Result of matrix multiplication (Exercise 3):\n", result)


Random Tensor (Exercise 2):
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Result of matrix multiplication (Exercise 3):
 tensor([[-1.2366],
        [-5.3767],
        [ 0.2430]])


In [5]:
#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)


In [6]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

# Check for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU is not available, using CPU instead")

# Set the random seed
torch.manual_seed(1234)

# Create two random tensors of shape (2, 3)
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# Move tensors to the GPU
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)


GPU is not available, using CPU instead
Tensor 1:
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
Tensor 2:
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [7]:
#

# Adjust the shape of tensor2 to be compatible with tensor1 for matrix multiplication
tensor2_resized = tensor2.T  # Transpose tensor2

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_resized)

print("Result of matrix multiplication:\n", result)


Result of matrix multiplication:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


In [8]:
# Find the maximum and minimum values of the output of 7.



# Example: create a tensor
my_tensor = torch.tensor([2, 7, 1, 9, 4])

# Find max and min
max_val = torch.max(my_tensor)
min_val = torch.min(my_tensor)

print(f"Maximum: {max_val}")
print(f"Minimum: {min_val}")


Maximum: 9
Minimum: 1


In [9]:
#Find the maximum and minimum index values of the output of 7.

# Find the maximum and minimum values of the 'result' tensor
result = torch.matmul(tensor1, tensor2_resized)  # Recalculate 'result'

max_val = torch.max(result)
min_val = torch.min(result)

print(f"Maximum value in 'result' tensor: {max_val}")
print(f"Minimum value in 'result' tensor: {min_val}")

#To find the index of the maximum and minimum values
max_index = torch.argmax(result)
min_index = torch.argmin(result)

print(f"Index of maximum value in 'result' tensor: {max_index}")
print(f"Index of minimum value in 'result' tensor: {min_index}")


Maximum value in 'result' tensor: 0.5617256760597229
Minimum value in 'result' tensor: 0.3647301495075226
Index of maximum value in 'result' tensor: 3
Index of minimum value in 'result' tensor: 0


In [10]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.



# Set the random seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
tensor_1 = torch.rand(1, 1, 1, 10)

# Print the tensor and its shape
print("First Tensor:\n", tensor_1)
print("First Tensor Shape:", tensor_1.shape)

# Remove all the 1 dimensions
tensor_2 = tensor_1.squeeze()

# Print the new tensor and its shape
print("Second Tensor:\n", tensor_2)
print("Second Tensor Shape:", tensor_2.shape)


First Tensor:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
First Tensor Shape: torch.Size([1, 1, 1, 10])
Second Tensor:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Second Tensor Shape: torch.Size([10])
